#version: '3'
#
#services:
#  postgres:
#    image: 'postgres:13'
#    container_name: 'java-postgres'
#    ports:
#      - 5432:5432
#    environment:
#      - 'POSTGRES_USER=sa'
#      - 'POSTGRES_HOST_AUTH_METHOD=trust'
#      - 'POSTGRES_DB=java'

version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  # some configs

services:
  postgres:
    image: postgres:18
    restart: no
    networks:
      - app-network
    environment:
      POSTGRES_DB: lectures_java_course_demo
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    #        ports:
    #          - "5432:5432" # for debug
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init-db.sql
      #      - /home/someUser/someDisk/postgres/data:/var/lib/postgresql # директория вместо volume
      - postgres_data:/var/lib/postgresql
    entrypoint: ["bash", "-c", "docker-entrypoint.sh postgres"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d lectures_java_course_demo" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  jdbc_app:
    build: ..
    container_name: jdbc_app
    restart: no
    networks:
      - app-network
    ports:
      - "8080:8080" # открой localhost:8080 в браузере
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4096M
    tmpfs:
      - /tmp # Обязательно для java приложений