<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<parent>
    <groupId>com.osherovskaya.labs</groupId>
    <artifactId>iosys-lab1-m-java</artifactId>
    <version>1.0-SNAPSHOT</version>
</parent>

<artifactId>lab-1</artifactId>

<dependencies>
    <!-- Подключаем зависимости -->
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter</artifactId>
        <scope>test</scope>
    </dependency>
<!--    <dependency>-->
<!--        <groupId>org.projectlombok</groupId>-->
<!--        <artifactId>lombok</artifactId>-->
<!--    </dependency>-->
</dependencies>

<build>
    <plugins>
        <!-- Позволяем lombok вмешиваться в генерацию байткода -->
<!--        <plugin>-->
<!--            <groupId>org.apache.maven.plugins</groupId>-->
<!--            <artifactId>maven-compiler-plugin</artifactId>-->
<!--            <version>${maven.compiler.plugin.version}</version>-->
<!--            <configuration>-->
<!--                <annotationProcessorPaths>-->
<!--&lt;!&ndash;                    <path>&ndash;&gt;-->
<!--&lt;!&ndash;                        <groupId>org.projectlombok</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;                        <artifactId>lombok</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;                    </path>&ndash;&gt;-->
<!--                    <path>-->
<!--                        <groupId>org.projectlombok</groupId>-->
<!--                        <artifactId>lombok</artifactId>-->
<!--                        <version>${lombok.version}</version>-->
<!--                    </path>-->

<!--                </annotationProcessorPaths>-->
<!--            </configuration>-->
<!--        </plugin>-->

        <!-- Плагин для создания fat JAR + со всеми зависимостями -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>${maven.shade.plugin.version}</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>shade</goal>
                    </goals>
                    <configuration>
                        <!-- Создаем исполняемый JAR с указанием главного класса -->
                        <transformers>
                            <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                <mainClass>com.osherovskaya.labs.Main</mainClass>
                            </transformer>
                        </transformers>
                        <shadedArtifactAttached>true</shadedArtifactAttached>
                        <shadedClassifierName>fat</shadedClassifierName>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>

</project>
